### ISSUE TITLE
output naming

### ISSUE THREAD

**Issue by lmperry** [scitran-apps/dcm2niix#10]
If DICOM files are found in dcm2niix_input directory, the default naming convention is to use that name as the output: 

```MR.1.2.840.113619.2.353.4120.7575399.14732.1415640823.785.dcm | MR.1.2.840.113619.2.353.4120.7575399.14732.1415640823.785.dcm | dcm2niix_input.nii.gz | dcm2niix_input.nii.gz
-- | -- | -- | --
MR.1.2.840.113619.2.353.4120.7575399.14732.1415640823.785.dcm
dcm2niix_input.nii.gz
```
The run script could be modified to handle this better.

**Comment by neurolabusc** [comment]
The naming scheme depends a lot on how your center uses DICOM fields. Your current file naming is based on the folder name
```
      "default": "%f",
      "id": "-f"
```
usually a good default is the protocol name and series number
```
      "default": "%p_%s",
      "id": "-f"
```
Note with the latest source code you can even request that files are segmented into different output folders, e.g. if your center adds a participant ID, you could use "%i/%p_%s"
