### ISSUE TITLE
Optionally convert compressed dicom files

### ISSUE THREAD

**Issue by lmperry** [scitran-apps/dcm2niix#4]
For some types of DIOCM files compression can be applied to the image data which
will cause dcm2niix to fail. 

See:
https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Transfer_Syntaxes_and_Compressed_Images

**Comment by neurolabusc** [comment]
@lmperry - can you provide example images that use unsupported transfer syntaxes. If you compile it with the OpenJPEG library (as done with all releases) it will support JPEG2000 out of the box. The remaining transfer syntaxes exist in theory but I have never seen any in the wild.
